<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClientBanner', 'doctrine');

/**
 * BaseClientBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $banner_id
 * @property integer $client_id
 * @property Banner $Banner
 * @property Client $Client
 * 
 * @method integer      getBannerId()  Returns the current record's "banner_id" value
 * @method integer      getClientId()  Returns the current record's "client_id" value
 * @method Banner       getBanner()    Returns the current record's "Banner" value
 * @method Client       getClient()    Returns the current record's "Client" value
 * @method ClientBanner setBannerId()  Sets the current record's "banner_id" value
 * @method ClientBanner setClientId()  Sets the current record's "client_id" value
 * @method ClientBanner setBanner()    Sets the current record's "Banner" value
 * @method ClientBanner setClient()    Sets the current record's "Client" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_banner');
        $this->hasColumn('banner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banner', array(
             'local' => 'banner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}