<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BannerPosition', 'doctrine');

/**
 * BaseBannerPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $banner_id
 * @property integer $position_index
 * @property integer $delay
 * @property integer $show_label
 * @property integer $x_position
 * @property integer $y_position
 * @property Banner $Banner
 * 
 * @method integer        getBannerId()       Returns the current record's "banner_id" value
 * @method integer        getPositionIndex()  Returns the current record's "position_index" value
 * @method integer        getDelay()          Returns the current record's "delay" value
 * @method integer        getShowLabel()      Returns the current record's "show_label" value
 * @method integer        getXPosition()      Returns the current record's "x_position" value
 * @method integer        getYPosition()      Returns the current record's "y_position" value
 * @method Banner         getBanner()         Returns the current record's "Banner" value
 * @method BannerPosition setBannerId()       Sets the current record's "banner_id" value
 * @method BannerPosition setPositionIndex()  Sets the current record's "position_index" value
 * @method BannerPosition setDelay()          Sets the current record's "delay" value
 * @method BannerPosition setShowLabel()      Sets the current record's "show_label" value
 * @method BannerPosition setXPosition()      Sets the current record's "x_position" value
 * @method BannerPosition setYPosition()      Sets the current record's "y_position" value
 * @method BannerPosition setBanner()         Sets the current record's "Banner" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_position');
        $this->hasColumn('banner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('position_index', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('delay', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('show_label', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('x_position', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('y_position', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Banner', array(
             'local' => 'banner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}