<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Client', 'doctrine');

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property string $client_text
 * @property Project $Project
 * @property Doctrine_Collection $Client
 * 
 * @method integer             getProjectId()   Returns the current record's "project_id" value
 * @method string              getClientText()  Returns the current record's "client_text" value
 * @method Project             getProject()     Returns the current record's "Project" value
 * @method Doctrine_Collection getClient()      Returns the current record's "Client" collection
 * @method Client              setProjectId()   Sets the current record's "project_id" value
 * @method Client              setClientText()  Sets the current record's "client_text" value
 * @method Client              setProject()     Sets the current record's "Project" value
 * @method Client              setClient()      Sets the current record's "Client" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client');
        $this->hasColumn('project_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('client_text', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ClientBanner as Client', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}