<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BannerPosition', 'doctrine');

/**
 * BaseBannerPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $banner_id
 * @property string $position_index
 * @property integer $x_start
 * @property integer $y_start
 * @property integer $x_end
 * @property integer $y_end
 * @property Project $Project
 * 
 * @method integer        getBannerId()       Returns the current record's "banner_id" value
 * @method string         getPositionIndex()  Returns the current record's "position_index" value
 * @method integer        getXStart()         Returns the current record's "x_start" value
 * @method integer        getYStart()         Returns the current record's "y_start" value
 * @method integer        getXEnd()           Returns the current record's "x_end" value
 * @method integer        getYEnd()           Returns the current record's "y_end" value
 * @method Project        getProject()        Returns the current record's "Project" value
 * @method BannerPosition setBannerId()       Sets the current record's "banner_id" value
 * @method BannerPosition setPositionIndex()  Sets the current record's "position_index" value
 * @method BannerPosition setXStart()         Sets the current record's "x_start" value
 * @method BannerPosition setYStart()         Sets the current record's "y_start" value
 * @method BannerPosition setXEnd()           Sets the current record's "x_end" value
 * @method BannerPosition setYEnd()           Sets the current record's "y_end" value
 * @method BannerPosition setProject()        Sets the current record's "Project" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_position');
        $this->hasColumn('banner_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('position_index', 'string', 22, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 22,
             ));
        $this->hasColumn('x_start', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('y_start', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('x_end', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('y_end', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'banner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}