<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/26 09:32:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/tmp/sf_sandbox/data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
