<?php

/**
 * bannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('banner');
    }
}