<?php

/**
 * BannerPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BannerPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BannerPosition');
    }
  
    public function getBannerPositionsFromBanner($banner)
    {
      $q = $this->createQuery('j')
        ->where('j.banner_id = ?',$banner);
 
      return $q->execute();
    }

    public function getBannerPositionsFromClient($clientId)
    {
      $q = $this->createQuery('j')
        ->where('j.client_id = ?',$clientId);
 
      return $q->execute();
    }

}
