<?php

/**
 * BannerPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BannerPosition extends BaseBannerPosition
{
    public function showBannerPositionImage(){
       $banner = Doctrine_Core::getTable('Banner')->find(array($this->getBannerId()));
       $url = sprintf('/uploads/banner/frames/%03d%s',$this->getPositionIndex(),$banner->getImageUrl());
       return $url;
    }
    
    public function showTestImage(){
       $banner = Doctrine_Core::getTable('Banner')->find(array($this->getBannerId()));
       $url = sprintf('/banner/client/%s/frames/%03d%s',$banner->sha1ImageText(),$this->getPositionIndex(),$banner->getImageUrl());
       if (!file_exists(sfConfig::get('sf_upload_dir').$url)) {
         //create new test banner
         $clientBanner = new ClientBanner();
         $clientBanner->setClientText($banner->getImageText());
         $clientBanner->setBannerId($banner->getId());
         $clientBanner->save();
       }
       return '/uploads'.$url;
    }

    public function showOriginalBanner(){
      $banner = Doctrine_Core::getTable('Banner')->find(array($this->getBannerId()));
      return $banner->getImageUrlAbsolute();
    }
}
