<?php

/**
 * ClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Client');
    }

    public function getClientByClientText($clientText)
    {
      $q = $this->createQuery('j')
        ->where('j.client_text = ?',$clientText);
      return $q->execute();
      
    }

}
