<?php

/**
 * ClientBannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientBannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientBannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientBanner');
    }

    public function getClientBannerByClientText($clientText)
    {
      $q = $this->createQuery('j')
        ->where('j.client_text = ?',$clientText);

      return $q->execute();
    }

}
