<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
  public function save(Doctrine_Connection $conn = null)
  {
    // create the clientbanner
    $banners = Doctrine_Core::getTable('Banner')->getBannersFromProject($this->getProjectId());
    foreach ($banners as $banner) {
      $bannerPositions = Doctrine_Core::getTable('BannerPosition')->getBannerPositionsFromBanner($banner->getId());
      include_once ( sfConfig::get('sf_root_dir').'/custom/GIFEncoder.class.php' );
      $dir = sfConfig::get('sf_upload_dir').sprintf('/banner/client/%s/',$this->sha1ClientText());
      if (!is_dir($dir)){
        //create the dir
        mkdir($dir);
        mkdir($dir.'/frames');
      }
      //first copy source files to clientbanner
      $dirHandle=opendir($banner->getFrameDir());
      while($file=readdir($dirHandle))
      {
        if($file!="." && $file!=".." && (strpos($file,$banner->getFileName())>0))
        {
          copy($banner->getFrameDir().$file,$this->getFrameDir().$file);
        }
      }
      closedir($dirHandle);

      foreach ($bannerPositions as $bannerPosition) {
        $positionIndex = $bannerPosition->getPositionIndex();
        $im = imagecreatefromgif($banner->getFramePath($positionIndex,$this->sha1ClientText()));
        #imagesavealpha($im, true);
        #imagealphablending($im, false);
        //add text
        if ($bannerPosition->getShowLabel()) {
          #$w = imagesx($im);
          #$h = imagesy($im);
          #list ($w, $h) = @getimagesize ($banner->getFramePath($positionIndex,$this->sha1ClientText())); 
          #$imgSize = @getimagesize ($banner->getFramePath($positionIndex,$this->sha1ClientText())); 
          #var_dump($imgSize);
          $text_color = imagecolorallocate($im, 0, 0, 0);
          $font = '/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf';
          $fontSize = $banner->getFontSize();
          $x = $bannerPosition->getXPosition();
          $y = $bannerPosition->getYPosition();
          #imagecolortransparent($im, $text_color);
          imagettftext($im, $fontSize, 0, $x, $y + $fontSize, $text_color, $font,  $this->getClientText());
        }
        imagegif($im,$banner->getFramePath($positionIndex,$this->sha1ClientText()));
        imagedestroy($im);

        $frames[] = $banner->getFramePath($positionIndex,$this->sha1ClientText());
        $framed[] = $bannerPosition->getDelay(); //get delaytimes from original!!!!
      }
      $gif = new GIFEncoder    (
                            $frames,
                            $framed,
                            0,
                            0,
                            0, 0, 0,
                            "url"
        );
      fwrite ( fopen ( $banner->getPath($this->sha1ClientText()), "wb" ), $gif->GetAnimation ( ) );
    }
    return parent::save($conn);
  }

  public function sha1ClientText(){
    return sha1($this->getClientText());
  }

  public function getFrameDir(){
    $url = sprintf('/banner/client/%s/frames/',$this->sha1ClientText());
    return sfConfig::get('sf_upload_dir').$url;
  }
  
  public function getDir(){
    $url = sprintf('/banner/client/%s/',$this->sha1ClientText());
    return sfConfig::get('sf_upload_dir').$url;
  }

  public function getClientBanners() {
    $banners = Doctrine_Core::getTable('Banner')->getBannersFromProject($this->getProjectId());
    return $banners;
  }

  public function getBannerUrl($bannerId){
    $banner = Doctrine_Core::getTable('Banner')->find(array($bannerId));
    $file = $banner->getFileName();
    return $this->getFrameDir().$file;
  }

  public function getBannerPath($bannerId){
    $banner = Doctrine_Core::getTable('Banner')->find(array($bannerId));
    $file = $banner->getFileName();
    return $this->getDir().$file;
  }
}
