<?php

/**
 * ClientBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Joeri de Bruin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClientBanner extends BaseClientBanner
{
    public function getBannerUrl(){
      $banner = Doctrine_Core::getTable('Banner')->find(array($this->getBannerId()));
      return $banner->getBannerUrl();
    }
    
    public function getBanner(){
      $banner = Doctrine_Core::getTable('Banner')->find(array($this->getBannerId()));
      return $banner;
    }
}
