# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Banner Project
    #description:  symfony project
    #keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    [master.css,colorpicker.css]

  javascripts:    [jquery.js,colorpicker.js,eye.js,utils.js,layout.js]

  has_layout:     true
  layout:         layout
