<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/01/31 13:51:39
return array(

  // sfThumbnailPlugin_module_libs

  // sfThumbnailPlugin_lib
  'sfgdadapter' => '/var/www/sf_sandbox/plugins/sfThumbnailPlugin/lib/sfGDAdapter.class.php',
  'sfimagemagickadapter' => '/var/www/sf_sandbox/plugins/sfThumbnailPlugin/lib/sfImageMagickAdapter.class.php',
  'sfthumbnail' => '/var/www/sf_sandbox/plugins/sfThumbnailPlugin/lib/sfThumbnail.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sftesterdoctrine' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinebuildtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinedqltask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinemigratetask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinebasetask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinecli' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'swift_doctrinespool' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrinecolumn' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinegenerator' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinepager' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfformfilterdoctrine' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineroute' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/var/www/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',

  // project
  'projectformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/ProjectFormFilter.class.php',
  'clientbannerformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/ClientBannerFormFilter.class.php',
  'bannerpositionformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/BannerPositionFormFilter.class.php',
  'bannerformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/BannerFormFilter.class.php',
  'basebannerpositionformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/base/BaseBannerPositionFormFilter.class.php',
  'baseprojectformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/base/BaseProjectFormFilter.class.php',
  'baseclientbannerformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/base/BaseClientBannerFormFilter.class.php',
  'basebannerformfilter' => '/var/www/sf_sandbox/lib/filter/doctrine/base/BaseBannerFormFilter.class.php',
  'baseformfilterdoctrine' => '/var/www/sf_sandbox/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'baseform' => '/var/www/sf_sandbox/lib/form/BaseForm.class.php',
  'bannerpositionform' => '/var/www/sf_sandbox/lib/form/doctrine/BannerPositionForm.class.php',
  'clientbannerform' => '/var/www/sf_sandbox/lib/form/doctrine/ClientBannerForm.class.php',
  'baseformdoctrine' => '/var/www/sf_sandbox/lib/form/doctrine/BaseFormDoctrine.class.php',
  'bannerform' => '/var/www/sf_sandbox/lib/form/doctrine/BannerForm.class.php',
  'projectform' => '/var/www/sf_sandbox/lib/form/doctrine/ProjectForm.class.php',
  'basebannerform' => '/var/www/sf_sandbox/lib/form/doctrine/base/BaseBannerForm.class.php',
  'baseclientbannerform' => '/var/www/sf_sandbox/lib/form/doctrine/base/BaseClientBannerForm.class.php',
  'baseprojectform' => '/var/www/sf_sandbox/lib/form/doctrine/base/BaseProjectForm.class.php',
  'basebannerpositionform' => '/var/www/sf_sandbox/lib/form/doctrine/base/BaseBannerPositionForm.class.php',

  // project_model
  'bannerpositiontable' => '/var/www/sf_sandbox/lib/model/doctrine/BannerPositionTable.class.php',
  'bannerposition' => '/var/www/sf_sandbox/lib/model/doctrine/BannerPosition.class.php',
  'project' => '/var/www/sf_sandbox/lib/model/doctrine/Project.class.php',
  'projecttable' => '/var/www/sf_sandbox/lib/model/doctrine/ProjectTable.class.php',
  'clientbanner' => '/var/www/sf_sandbox/lib/model/doctrine/ClientBanner.class.php',
  'banner' => '/var/www/sf_sandbox/lib/model/doctrine/Banner.class.php',
  'basebanner' => '/var/www/sf_sandbox/lib/model/doctrine/base/BaseBanner.class.php',
  'baseproject' => '/var/www/sf_sandbox/lib/model/doctrine/base/BaseProject.class.php',
  'baseclientbanner' => '/var/www/sf_sandbox/lib/model/doctrine/base/BaseClientBanner.class.php',
  'basebannerposition' => '/var/www/sf_sandbox/lib/model/doctrine/base/BaseBannerPosition.class.php',
  'bannertable' => '/var/www/sf_sandbox/lib/model/doctrine/BannerTable.class.php',
  'clientbannertable' => '/var/www/sf_sandbox/lib/model/doctrine/ClientBannerTable.class.php',

  // application
  'myuser' => '/var/www/sf_sandbox/apps/frontend/lib/myUser.class.php',

  // modules
);
