<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/01/26 14:42:30
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Users/rory/Sites/sf_sandbox/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'bannerformfilter' => '/Users/rory/Sites/sf_sandbox/lib/filter/doctrine/bannerFormFilter.class.php',
  'basebannerformfilter' => '/Users/rory/Sites/sf_sandbox/lib/filter/doctrine/base/BasebannerFormFilter.class.php',
  'baseprojectformfilter' => '/Users/rory/Sites/sf_sandbox/lib/filter/doctrine/base/BaseprojectFormFilter.class.php',
  'baseformfilterdoctrine' => '/Users/rory/Sites/sf_sandbox/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'projectformfilter' => '/Users/rory/Sites/sf_sandbox/lib/filter/doctrine/projectFormFilter.class.php',
  'baseform' => '/Users/rory/Sites/sf_sandbox/lib/form/BaseForm.class.php',
  'bannerform' => '/Users/rory/Sites/sf_sandbox/lib/form/doctrine/bannerForm.class.php',
  'basebannerform' => '/Users/rory/Sites/sf_sandbox/lib/form/doctrine/base/BasebannerForm.class.php',
  'baseprojectform' => '/Users/rory/Sites/sf_sandbox/lib/form/doctrine/base/BaseprojectForm.class.php',
  'baseformdoctrine' => '/Users/rory/Sites/sf_sandbox/lib/form/doctrine/BaseFormDoctrine.class.php',
  'projectform' => '/Users/rory/Sites/sf_sandbox/lib/form/doctrine/projectForm.class.php',

  // project_model
  'banner' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/banner.class.php',
  'bannertable' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/bannerTable.class.php',
  'basebanner' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/base/Basebanner.class.php',
  'baseproject' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/base/Baseproject.class.php',
  'project' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/project.class.php',
  'projecttable' => '/Users/rory/Sites/sf_sandbox/lib/model/doctrine/projectTable.class.php',

  // application
  'myuser' => '/Users/rory/Sites/sf_sandbox/apps/frontend/lib/myUser.class.php',

  // modules
);
