<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/28 16:39:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bannerproject',
  'username' => 'root',
  'password' => 'joppi3ee',
  'name' => 'doctrine',
)),);
