Banner:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: banner
  columns:
    project_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image_url:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    image_text:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    text_font:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    text_color:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    font_size:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Project: { onDelete: CASCADE, local: project_id, foreign: id, foreignAlias: Projects } 

BannerPosition:
  connection: doctrine
  tableName: banner_position
  columns:
    banner_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    position_index:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    delay:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    show_label:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    x_position:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_position:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Banner: { onDelete: CASCADE, local: banner_id, foreign: id, foreignAlias: Banners } 

Client:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: client
  columns:
    project_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    client_text: 
      type: string(255)
  relations:
    Project: { onDelete: CASCADE, local: project_id, foreign: id, foreignAlias: Projects } 

ClientBanner:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: client_banner
  columns:
    banner_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    client_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Banner: { onDelete: CASCADE, local: banner_id, foreign: id, foreignAlias: Banners } 
    Client: { onDelete: CASCADE, local: client_id, foreign: id, foreignAlias: Client } 

Project:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: project
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    url:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    header:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
