Banner:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: banner
  columns:
    project_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image_url:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    image_text:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    text_font:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Project: { onDelete: CASCADE, local: project_id, foreign: id, foreignAlias: Projects } 

BannerPosition:
  connection: doctrine
  tableName: banner_position
  columns:
    banner_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    position_index:
      type: string(22)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    x_start:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_start:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    x_end:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_end:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
  relations:
    Project: { onDelete: CASCADE, local: banner_id, foreign: id, foreignAlias: Banners } 

ClientBanner:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: client_banner
  columns:
    banner_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    client_text: 
      type: string(255)
  relations:
    Banner: { onDelete: CASCADE, local: banner_id, foreign: id, foreignAlias: Banners } 

Project:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: project
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    url:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    header:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
